//! Turns `game-levels.json` into Rust data, so the Wasm carries no JSON parser. Mobile
//! overrides are applied here, and invalid monster or tower names fail the build.
use std::{env, fmt::Write as _, fs, path::PathBuf};

use serde_json::{Map, Value};

const MONSTERS: [(&str, &str); 8] = [
    ("packman", "PackMan"),
    ("square", "Square"),
    ("triangle", "Triangle"),
    ("tank", "Tank"),
    ("runner", "Runner"),
    ("splitter", "Splitter"),
    ("berserker", "Berserker"),
    ("bulwark", "Bulwark"),
];
const TOWERS: [(&str, &str); 6] = [
    ("gun", "Gun"),
    ("laser", "Laser"),
    ("missile", "Missile"),
    ("slow", "Slow"),
    ("drone", "Drone"),
    ("lightning", "Lightning"),
];

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let levels_path = manifest.join("../../game-levels.json");
    println!("cargo:rerun-if-changed={}", levels_path.display());
    let text = fs::read_to_string(&levels_path).expect("read game-levels.json");
    let levels: Vec<Map<String, Value>> = serde_json::from_str(&text).expect("parse game-levels.json");

    let mut out = String::from("// Generated by build.rs from game-levels.json.\n");
    for (name, mobile) in [("DESKTOP_ROUTES", false), ("MOBILE_ROUTES", true)] {
        writeln!(out, "pub static {name}: &[RouteData] = &[").unwrap();
        for level in &levels {
            let mut merged = level.clone();
            merged.remove("mobile");
            if mobile && let Some(Value::Object(overrides)) = level.get("mobile") {
                for (key, value) in overrides {
                    merged.insert(key.clone(), value.clone());
                }
            }
            write_route(&mut out, &merged);
        }
        out.push_str("];\n");
    }
    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("levels.rs");
    fs::write(dest, out).expect("write levels.rs");
}

fn write_route(out: &mut String, level: &Map<String, Value>) {
    let name = level["name"].as_str().expect("level name");
    let number = |key: &str| level.get(key).and_then(Value::as_f64);
    let optional = |value: Option<f64>| value.map_or("None".to_string(), |v| format!("Some({v:?})"));
    let sequence = level["monsterSequence"].as_array().expect("monsterSequence");
    assert!(!sequence.is_empty(), "Level \"{name}\" must define a non-empty monsterSequence.");
    let monsters: Vec<String> = sequence
        .iter()
        .map(|value| {
            let id = value.as_str().unwrap_or_default();
            let (_, variant) = MONSTERS
                .iter()
                .find(|(candidate, _)| *candidate == id)
                .unwrap_or_else(|| panic!("Level \"{name}\" has invalid monster \"{id}\" in monsterSequence."));
            format!("MonsterKind::{variant}")
        })
        .collect();
    let mut towers: Vec<&str> = Vec::new();
    for value in level["availableTowers"].as_array().expect("availableTowers") {
        let id = value.as_str().unwrap_or_default();
        let (_, variant) = TOWERS
            .iter()
            .find(|(candidate, _)| *candidate == id)
            .unwrap_or_else(|| panic!("Level \"{name}\" has invalid tower \"{id}\" in availableTowers."));
        if !towers.contains(variant) {
            towers.push(variant);
        }
    }
    assert!(!towers.is_empty(), "Level \"{name}\" must have at least one available tower.");
    let points: Vec<String> = level["points"]
        .as_array()
        .expect("points")
        .iter()
        .map(|point| {
            let pair = point.as_array().expect("point pair");
            format!("Point::new({:?}, {:?})", pair[0].as_f64().unwrap(), pair[1].as_f64().unwrap())
        })
        .collect();
    let subtitle = level.get("subtitle").and_then(Value::as_str).map_or("None".to_string(), |s| format!("Some({s:?})"));
    writeln!(
        out,
        "    RouteData {{ name: {name:?}, subtitle: {subtitle}, allow_escape: {}, starting_money: {}, wave_count: {}, initial_build_time: {}, monster_sequence: &[{}], available_towers: &[{}], points: &[{}] }},",
        number("allowEscape").expect("allowEscape") as i32,
        number("startingMoney").expect("startingMoney") as i32,
        number("waveCount").map_or("None".to_string(), |v| format!("Some({})", v as usize)),
        optional(number("initialBuildTime")),
        monsters.join(", "),
        towers.iter().map(|variant| format!("TowerKind::{variant}")).collect::<Vec<_>>().join(", "),
        points.join(", "),
    )
    .unwrap();
}
